enable-magisk-update = true
logging-to-file = true
compression-level = 9
parallel-jobs = 1

patches-version = "dev"   # 'latest', 'dev', or a version number. default: "latest"
cli-version = "latest"       # 'latest', 'dev', or a version number. default: "latest"

[YouTube]
enabled = true
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "both"
include-stock = true
riplib = true
arch = "arm64-v8a"
dpi = "nodpi"
patcher-args = "-e 'Hide Shorts components' -OhideShortsAppShortcut=true -OhideShortsWidget=true"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"
github_release-dlurl = "https://github.com/E85Addict/APKs/releases/latest"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
